#!/usr/bin/env bash
# How to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing config

sudo nginx -t
sudo service nginx reload
