#!/usr/bin/env bash
# Customising a 404 page

# Nginx installation
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Site redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Willys12 permanenr;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement" /etc/nginx/sites-enabled/default

# Restarting nginx
sudo service nginx restart
