#!/usr/bin/env bash

# UFW installation.
sudo apt update
sudo apt install ufw

# UFW Configuration.
sudo ufw disable
sudo ufw reset
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw allow 8080/tcp

# Starting up ufw.
sudo ufw enable

# Enabling packet forwarding
echo 'net/ipv4/ip_forward=1' | sed tee -a /etc/ufw/sysctl.conf

#Configuring port forwarding

sudo bash -c 'cat <<EOF >> /etc/ufw/before.rules
#starting port forwarding
*nat
:PREROUTING ACCEPT [0:0]

# forward port 8080 to 80
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

COMMIT
#end of Port forwarding
EOF'

# Enable ufw
sudo reload
sudo systemctl restart ufw
sudo ufw status
